export const LOGIN_USER = 'LOGIN_USER'
export const SET_USER = 'SET_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const GET_USER = 'GET_USER'
export const GET_USERS = 'GET_USERS'
export const NEW_USER = 'NEW_USER'
export const SAVE_PROJ = 'SAVE_PROJ'
export const GET_PROJS = 'GET_PROJS'
